name: CI

on:
  push:
    branches: [ main, master, develop, feature/** ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'    # match your local Python; change if needed
          cache: 'pip'              # speed up: caches pip downloads by hash of requirements.txt
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest -q --maxfail=1 --disable-warnings

      # Publish a JUnit report artifact (useful for if tests fail)
      - name: Run tests with JUnit report
        if: always()
        run: |
          python -m pytest --junitxml=test-results.xml || true 
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: test-results.xml
          if-no-files-found: ignore
      